"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 21:33:41.893092
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_norm', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('valid', 'invalid', 'catch_all', 'risky', 'disposable', 'role_based', 'syntax_error', 'domain_error', 'unknown', name='emailstatus', native_enum=False), nullable=False),
    sa.Column('sub_status', sa.String(length=120), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_email_norm'), ['email_norm'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('name_norm', sa.String(length=255), nullable=False),
    sa.Column('email_norm', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_norm')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_name_norm'), ['name_norm'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('respect_robots', sa.Boolean(), nullable=False),
    sa.Column('render_js', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_rps', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('tos_notes', sa.Text(), nullable=True),
    sa.Column('tos_reviewed_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('suppression',
    sa.Column('email_norm', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email_norm')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('sidecar_count', sa.Integer(), nullable=False),
    sa.Column('available_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'number', name='uq_batch_category_number')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('template_key', sa.String(length=128), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_run_id'), ['run_id'], unique=False)

    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fetched', 'blocked', 'failed', 'extracted', name='capturestatus', native_enum=False), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('html_path', sa.Text(), nullable=True),
    sa.Column('text_path', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('search_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url', 'category_id', name='uq_capture_url_category')
    )
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captures_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_domain'), ['domain'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_norm', sa.String(length=320), nullable=True),
    sa.Column('item_sought', sa.String(length=120), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('date_posted_raw', sa.String(length=120), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('intent_phrase', sa.String(length=120), nullable=True),
    sa.Column('extractor', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('email_status', sa.Enum('valid', 'invalid', 'catch_all', 'risky', 'disposable', 'role_based', 'syntax_error', 'domain_error', 'unknown', name='emailstatus', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('extracted', 'rejected', 'qualified', 'verified', 'duplicate', 'pending_review', 'approved', 'rejected_review', 'exported', name='candidatestatus', native_enum=False), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_id', 'email_norm', 'request_fingerprint', name='uq_candidate_capture_person_item')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_email_norm'), ['email_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_request_fingerprint'), ['request_fingerprint'], unique=False)
        batch_op.create_index('ix_candidates_status_category', ['status', 'category_id'], unique=False)

    op.create_table('batch_items',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('batch_id', 'candidate_id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('duplicate_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('edits', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decisions')
    op.drop_table('duplicate_links')
    op.drop_table('batch_items')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_status_category')
        batch_op.drop_index(batch_op.f('ix_candidates_request_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_candidates_email_norm'))

    op.drop_table('candidates')
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captures_domain'))
        batch_op.drop_index(batch_op.f('ix_captures_canonical_url'))

    op.drop_table('captures')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_events_run_id'))

    op.drop_table('usage_events')
    op.drop_table('queries')
    op.drop_table('runs')
    op.drop_table('batches')
    op.drop_table('suppression')
    op.drop_table('sources')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_name_norm'))

    op.drop_table('people')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_email_norm'))

    op.drop_table('email_verifications')
    op.drop_table('categories')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
